repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        name: "Ruff Linter"
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        name: "Ruff Formatter"
        types_or: [python, pyi]

  # isort for import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: "isort (import sorting)"
        args: ["--profile", "black"]

  # mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        name: "MyPy Type Checker"
        additional_dependencies:
          - httpx
          - injector
          - pillow
        exclude: ^tests/
        args: [--config-file=pyproject.toml]

  # Basic quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: "Remove trailing whitespace"
      - id: end-of-file-fixer
        name: "Ensure files end with newline"
      - id: check-yaml
        name: "Validate YAML files"
      - id: check-toml
        name: "Validate TOML files"
      - id: check-merge-conflict
        name: "Check for merge conflict markers"
      - id: check-added-large-files
        name: "Prevent large files from being committed"
        args: ['--maxkb=500']

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        name: "Bandit Security Linter"
        args: ['-c', 'pyproject.toml']
        exclude: ^tests/
